//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int SongId { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual User User { get; set; }

        public Comment(int id, string text, DateTime date, int userId, int songId)
        {
            Id = id;
            Text = text;
            Date = date;
            UserId = userId;
            SongId = songId;
        }

        public Comment(string text, DateTime date, int userId, int songId)
        {
            Text = text;
            Date = date;
            UserId = userId;
            SongId = songId;
        }

        public Comment()
        {
        }

        public override string ToString()
        {
            return "Comment{" +
                 "Id=" + Id +
                 ", Text='" + Text + '\'' +
                 ", UserId=" + UserId +
                 ", Date=" + Date +
                 ", SongId=" + SongId +
                 '}';
        }

        public override bool Equals(object obj)
        {
            var comment = obj as Comment;
            return comment != null &&
                   Id == comment.Id &&
                   Text == comment.Text &&
                   Date == comment.Date &&
                   UserId == comment.UserId &&
                   SongId == comment.SongId;
        }

        public override int GetHashCode()
        {
            var hashCode = -147973881;
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Text);
            hashCode = hashCode * -1521134295 + Date.GetHashCode();
            hashCode = hashCode * -1521134295 + UserId.GetHashCode();
            hashCode = hashCode * -1521134295 + SongId.GetHashCode();
            return hashCode;
        }
    }
}
