//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.UserMessages = new HashSet<UserMessage>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int UserSenderId { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMessage> UserMessages { get; set; }

        public Message(int id, string text, int senderId, DateTime date)
        {
            Id = id;
            Text = text;
            UserSenderId = senderId;
            Date = date;
        }

        public Message(string text, int senderId, DateTime date)
        {
            Text = text;
            UserSenderId = senderId;
            Date = date;
        }

      


        public override string ToString()
        {
            return "Message{" +
                "Id=" + Id +
                ", Text='" + Text + '\'' +
                ", UserSenderId=" + UserSenderId +
                ", Date=" + Date +
                '}';
        }

        public override bool Equals(object obj)
        {
            var message = obj as Message;
            return message != null &&
                   Text == message.Text &&
                   UserSenderId == message.UserSenderId &&
                   Date == message.Date;
        }

        public override int GetHashCode()
        {
            var hashCode = -187055288;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Text);
            hashCode = hashCode * -1521134295 + UserSenderId.GetHashCode();
            hashCode = hashCode * -1521134295 + Date.GetHashCode();
            return hashCode;
        }
    }
}
