//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageConclusionTime
    {
        public int Id { get; set; }
        public int FirstUserId { get; set; }
        public int SecondUserId { get; set; }
        public System.DateTime FirstUserDate { get; set; }
        public System.DateTime SecondUserDate { get; set; }
        public MessageConclusionTime(int id, int firstUserId, int secondUserId, DateTime firstUserDate, DateTime secondUserDate)
        {
            Id = id;
            FirstUserId = firstUserId;
            SecondUserId = secondUserId;
            FirstUserDate = firstUserDate;
            SecondUserDate = secondUserDate;
        }

        public MessageConclusionTime(int firstUserId, int secondUserId, DateTime firstUserDate, DateTime secondUserDate)
        {
            FirstUserId = firstUserId;
            SecondUserId = secondUserId;
            FirstUserDate = firstUserDate;
            SecondUserDate = secondUserDate;
        }

        public MessageConclusionTime()
        {
        }

        public override bool Equals(object obj)
        {
            var time = obj as MessageConclusionTime;
            return time != null &&
                   Id == time.Id &&
                   FirstUserId == time.FirstUserId &&
                   SecondUserId == time.SecondUserId &&
                   FirstUserDate == time.FirstUserDate &&
                   SecondUserDate == time.SecondUserDate;
        }

        public override int GetHashCode()
        {
            var hashCode = 211627914;
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + FirstUserId.GetHashCode();
            hashCode = hashCode * -1521134295 + SecondUserId.GetHashCode();
            hashCode = hashCode * -1521134295 + FirstUserDate.GetHashCode();
            hashCode = hashCode * -1521134295 + SecondUserDate.GetHashCode();
            return hashCode;
        }

        public override string ToString()
        {
            return "MessageConclusionTime{" +
               "Id=" + Id +
               ", FirstUserId=" + FirstUserId +
               ", SecondUserId=" + SecondUserId +
               ", FirstUserDate=" + FirstUserDate +
               ", SecondUserDate=" + SecondUserDate +
               '}';
        }
    }
}
