//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayListSong
    {
        public int Id { get; set; }
        public int SongId { get; set; }
        public int PlayListId { get; set; }
    
        public virtual PlayList PlayList { get; set; }
        public virtual Song Song { get; set; }
        public PlayListSong(int id, int songId, int playListId)
        {
            Id = id;
            SongId = songId;
            PlayListId = playListId;
        }

        public PlayListSong(int songId, int playListId)
        {
            SongId = songId;
            PlayListId = playListId;
        }

        public PlayListSong()
        {
        }

        public override bool Equals(object obj)
        {
            var song = obj as PlayListSong;
            return song != null &&
                   Id == song.Id &&
                   SongId == song.SongId &&
                   PlayListId == song.PlayListId;
        }

        public override int GetHashCode()
        {
            var hashCode = -16023929;
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + SongId.GetHashCode();
            hashCode = hashCode * -1521134295 + PlayListId.GetHashCode();
            return hashCode;
        }

        public override string ToString()
        {
            return "PlayListSong{" +
                "Id=" + Id +
                ", SongId=" + SongId +
                ", PlayListId=" + PlayListId +
                '}';
        }
    }
}
