//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Comments = new HashSet<Comment>();
            this.PlayListSongs = new HashSet<PlayListSong>();
        }
    
        public int Id { get; set; }
        public string LocalUrl { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string AuthorName { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Album { get; set; }
        public int Duraction { get; set; }
        public int NumberOfPlays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayListSong> PlayListSongs { get; set; }
        public Song(string localUrl, string name, string description, string type, string authorName, DateTime releaseDate, string album, int duraction, int numberOfPlays)
        {
            LocalUrl = localUrl;
            Name = name;
            Description = description;
            Type = type;
            AuthorName = authorName;
            ReleaseDate = releaseDate;
            Album = album;
            Duraction = duraction;
            NumberOfPlays = numberOfPlays;
        }

        public Song(int id, string localUrl, string name, string description, string type, string authorName, DateTime releaseDate, string album, int duraction, int numberOfPlays)
        {
            Id = id;
            LocalUrl = localUrl;
            Name = name;
            Description = description;
            Type = type;
            AuthorName = authorName;
            ReleaseDate = releaseDate;
            Album = album;
            Duraction = duraction;
            NumberOfPlays = numberOfPlays;
        }

      

        public override bool Equals(object obj)
        {
            var song = obj as Song;
            return song != null &&
                   Id == song.Id &&
                   LocalUrl == song.LocalUrl &&
                   Name == song.Name &&
                   Description == song.Description &&
                   Type == song.Type &&
                   AuthorName == song.AuthorName &&
                   ReleaseDate == song.ReleaseDate &&
                   Album == song.Album &&
                   Duraction == song.Duraction &&
                   NumberOfPlays == song.NumberOfPlays;
        }

        public override int GetHashCode()
        {
            var hashCode = 1013002190;
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(LocalUrl);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Name);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Description);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Type);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(AuthorName);
            hashCode = hashCode * -1521134295 + ReleaseDate.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Album);
            hashCode = hashCode * -1521134295 + Duraction.GetHashCode();
            hashCode = hashCode * -1521134295 + NumberOfPlays.GetHashCode();
            return hashCode;
        }

        public override string ToString()
        {
            return "Song{" +
                "Id=" + Id +
                ", LocalUrl='" + LocalUrl + '\'' +
                ", Name='" + Name + '\'' +
                ", Description='" + Description + '\'' +
                ", Type='" + Type + '\'' +
                ", AuthorName='" + AuthorName + '\'' +
                ", ReleaseDate='" + ReleaseDate +
                ", Album='" + Album + '\'' +
                ", Duraction=" + Duraction +
                ", NumberOfPlays=" + NumberOfPlays +
                '}';
        }
    }
}
