//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int UserGetterId { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }

        public UserMessage(int id, int messageId, int userId)
        {
            Id = id;
            MessageId = messageId;
            UserGetterId = userId;
        }

        public UserMessage(int messageId, int userId)
        {
            MessageId = messageId;
            UserGetterId = userId;
        }

        public UserMessage()
        {
        }

        public override bool Equals(object obj)
        {
            var message = obj as UserMessage;
            return message != null &&
                   Id == message.Id &&
                   MessageId == message.MessageId &&
                   UserGetterId == message.UserGetterId;
        }

        public override int GetHashCode()
        {
            var hashCode = 861166800;
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + MessageId.GetHashCode();
            hashCode = hashCode * -1521134295 + UserGetterId.GetHashCode();
            return hashCode;
        }

        public override string ToString()
        {
            return "UserMessage{" +
                "Id=" + Id +
                ", MessageId=" + MessageId +
                ", UserGetterId=" + UserGetterId +
                '}';
        }
    }
}
